### ISSUE TITLE
离线消息方案

### ISSUE THREAD

**Issue by fzdwx** [fzdwx/chat#3]
@liuwj-java @DesignerLookMe

**Comment by DesignerLookMe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fzdwx** [comment]
# 方案一
1. 服务端保存该用户与对应好友/频道的离线消息中最小的`msgId`，与所有会话的`离线消息未读数量`
2. 用户登录时，拉取所有会话的离线消息未读数量
3. 用户点击时，读取该用户的对应会话的未读离线消息，并清除对应的`离线未读数量`以及最小`msgId`

**Comment by fzdwx** [comment]
# 方案三
1. 引入seq，每个用户一个seq关系，`userid:seq`，每收到或发送一条消息就增加seq，然后将这条消息跟这个seq绑定
2. 这条消息的发送者和接收者各保存一条
3. 客户端保存这个所接收到的最大seq，上线时发送请求同步`(client_seq，server_seq]`之间的消息

@DesignerLookMe @liuwj-java

**Comment by fzdwx** [comment]
我的方案可以总结为：
1. 服务端保存这个用户收到的最大msgId
2. 客户端存最后一条msgId
3. 上线时发送请求同步 client msgId ~ serverMsgId

- 方案3需要把一条消息保存两份
- 方案1与方案2重复。
